backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'keyfigures'
    label: 'Key figures'
    folder: 'content/keyfigures'
    format: 'frontmatter'
    create: false
    fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Ships', name: 'ships', widget: 'number' }
    - { label: 'Years of Average Age', name: 'years', widget: 'number' }
    - { label: 'Milion tons', name: 'tons', widget: 'number' }
    - { label: 'Voyages', name: 'voyages', widget: 'number' }
    - { label: 'Port Calls', name: 'portcalls', widget: 'number' }
  - name: 'blog'
    label: 'Ships'
    folder: 'content/blog'
    format: 'frontmatter'
    sortable_fields: ['sortorder']
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'General Arrangement', name: 'manualga_pdf', widget: 'file', required: false }
      - { label: 'Capacity Plan', name: 'manualcp_pdf', widget: 'file', required: false }
      - { label: 'Sort order', name: 'sortorder', default: '1', widget: 'number' }